localization:
  args: ''
  autorun: true
  command: roslaunch turtlebot_navigation radio_amcl.launch
  params: scan_topic:=/hokuyo_base/scan
  process: ''
map_saver:
  args: ''
  command: rosrun map_server map_saver
  default_map: map1
  maps_folder: /home/rnavarro/workspaces/radio_ws/src/map_nav_manager/map
  params: ''
  process: ''
map_server:
  args: ''
  autorun: true
  command: rosrun map_server map_server
  default_map: map2
  maps_folder: /home/rnavarro/workspaces/radio_ws/src/map_nav_manager/map
  params: ''
  process: ''
mapping:
  args: ''
  autorun: false
  command: roslaunch turtlebot_navigation radio_gmapping.launch
  params: scan_topic:=/hokuyo_base/scan
  process: ''
navigation:
  args: ''
  autorun: true
  command: roslaunch turtlebot_navigation radio_move_base.launch
  params: scan_topic:=/hokuyo_base/scan local_planner:=teb
  process: ''
